### ISSUE TITLE
Suggestion: use here::here() to deal with working directories

### ISSUE THREAD

**Issue by stefanocoretta** [IPS-LMU/soundChangeR#2]
https://github.com/IPS-LMU/ABM/blob/4f405bd89a60c4d9c2e4f917df927746f2e52645/Rcmd/ABMmain.R#L13

I think for portability it would better to assume that the current working directory is always the ABM folder, and use paths relative to that. The `here::here()` function might come in handy if you do need to set directories. (I think not using `setwd()` at all is better in general, especially when using R projects/RStudio). Just a suggestion though.

**Comment by johannacronenberg** [comment]
Thanks for the suggestion, I wasn't familiar with `here()`! So would this be the way to go?
- Ask users to open RStudio,
- run `install.packages("here")`,
- set the working directory to the ABM folder, 
- `source(Rcmd/ABMmain.R)` where the first lines would then be:
```
library(here)
ABMpath <- here()
```
Because as far as I understand it, `here()` operates from the current working directory at the time of loading the library. So if users have opened RStudio, say, in their home directory instead of the ABM folder and do not `setwd(path/to/ABM)`, `here()` would default to their home directory (unless there is an `RProj` or `.here` file in any parent directory), correct?

**Comment by stefanocoretta** [comment]
Yes, that is in part correct (here searches for other files as well, like a .git/ folder). I just realised now that I was assuming that people would create an Rproj while using Rstudio so that here would always default to the ABM directory.

Some people don't use Rstudio at all, so there are two options the users can can choose from:

- Either they set the working directory to the `ABM/` directory at the beginning of their R session, every time they start a session (whether they use RStudio or not).
- Or they can create an Rproject in the `ABM/` directory if they use RStudio (you could even include the .Rproj file in the repo, so users wouldn't have to create it).

Independent of either of these solutions, you can just make all of the paths in the code relative (and assume that the working directory will always be `ABM/`, whether users use RStudio or not).

**Comment by johannacronenberg** [comment]
This issue was solved with the latest push to master.
